MyProject/urls.py
from django.conf.urls import url,include
from django.views.static import serve
from MyProject.settings import MEDIA_ROOT


import xadmin
xadmin.autodiscover()
from xadmin.plugins import xversion
xversion.register_models()

urlpatterns = [
    url(r'',xadmin.site.urls),
    url(r'media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^api-auth/', include('rest_framework.urls',namespace="rest_framework")),

    url(r'inclass/',include('inClass.urls')),
    url(r'interaction/',include('interaction.urls')),
    url(r'resource/',include('resource.urls')),

    # path('',include('student.urls')),
]

inClass/urls.py
from django.conf.urls import url
from . import views
# from django.urls import

app_name = "inClass"
urlpatterns = [
    url('api/material/',views.MateriaOperation.as_view()),
    url('api/paper/',views.getPaperList.as_view()),
    url('api/question/',views.getQuestion),
    url('api/choice/',views.getChoice),
]

student/urls.py
from django.urls import path
from . import views

app_name = "student"
urlpatterns = [
    path('',views.doLogin,name = "login"),
    path('register/',views.doRegister,name = "register"),
    path('index/',views.index,name = "index"),

    path('advice/',views.advice,name = "advice"),
    path('announcement/',views.announcement,name = "announcement"),
    path('article/',views.article,name = "article"),
    path('book/',views.book,name = "book"),
    path('interest/', views.interest, name="interest"),
    path('news/', views.news, name="news"),
    path('slice/', views.slice, name="slice"),
    path('textPaper/', views.textPaper, name="textPaper"),
    path('userInfor/', views.userInfor, name="userInfor"),
    path('video/', views.video, name="video"),
    path('viewShare/', views.viewShare, name="viewShare"),
    path('writeShare/', views.writeShare, name="writeShare"),


]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from resource.models import Video,Book,Article
from inClass.models import Material,Question,TestPaper,Choice
from interaction.models import Advice,Announcement,Share
import datetime

global srcLink
srcLink = "http://127.0.0.1:8000/media/"

# Create your views here.
def isRegister(username):
    try:
        User.objects.get(username=username)
    except User.DoesNotExist:
        return False
    return True

def doLogin(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST['password']
        user = authenticate(username = username,password = password)
        # 用户合法，保存session信息，进入index页面
        if user is not None:
            request.session["username"] = username
            request.session["password"] = password
            request.session.set_expiry(0)
            return HttpResponseRedirect(reverse('student:index'))
        # 不合法，返回原页面,提示用户不合法
        else:
            return render(request,'student/studentLogin.html',{"msg":True})
    else:
        return render(request,'student/studentLogin.html',{"msg":False})

def doRegister(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]
        # 已注册，提示已存在
        if isRegister(username):
            return render(request,'student/register.html',{"flag":True})
        # 未注册，创建用户后，跳转到登录界面
        else:
            User.objects.create_user(username=username,password=password,email=email)
            return render(request,'student/studentLogin.html',{"msg":False})
    else:
        return render(request,'student/register.html',{"flag":False})

def index(request):
    if "username" in request.session.keys() and "password"  in request.session.keys():
        username = request.session["username"]
        password = request.session["password"]
        user = authenticate(username = username,password = password)
        print(username)
        print(password)
        # 用户合法，跳转到index页面
        if user is not None:
            return render(request,'student/index.html',{"username":username})
        # 用户不合法，跳转到error页面
        else:
            return render(request,'student/error.html',{"errorMsg":"请先登录"})
    else:
        return render(request,'student/error.html',{"errorMsg":"请先登录"})

def advice(request):
    pass

def announcement(request):
    pass

def article(request):
    pass

def book(request):
    pass

def interest(request):
    pass

def news(request):
    pass

def slice(request):
    pass

def textPaper(request):
    pass

def userInfor(request):
    pass

def video(request):
    now = datetime.datetime.now()
    delta = datetime.timedelta(days=-7)
    datelimt = now+delta
    # 筛选近7天内发布的视频资料
    videolist = Video.objects.filter(status=2,pubtime__gte=datelimt).order_by("-pubtime")
    print(list(videolist)[0].area)
    return render(request,'student/video.html',{"videos":list(videolist),"srcLink":srcLink})

def viewShare(request):
    pass

def writeShare(request):
    pass

student/templates/student/advice.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'student/js/hui-form.js' %}"></script>
</head>
<body style="background-color: #ffffff;">
<div class="hui-wrap">
	<div class="hui-common-title" style="margin-top:15px;">
			<div class="hui-common-title-line"></div>
			<div class="hui-common-title-txt " style="font-size: 40px;">反馈意见</div>
			<div class="hui-common-title-line"></div>
		</div>

			<form class="hui-form" id="adviceForm" style="padding: 200px 400px;">
				
				<div class="hui-form-items">
					<div class="hui-form-items-title">意见标题</div>
					<input type="text" class="hui-input hui-input-clear" name="advice_title" 
						checkType="string" checkData="1,15" checkMsg="意见标题应为1-15个字符" placeholder="请填写标题"/>
				</div>
	
				<div class="hui-form-items">
					<div class="hui-form-items-title">意见内容</div>
					<div class="hui-form-textarea">
						<textarea name="advice_content" placeholder="请填写意见内容"></textarea>
					</div>
				</div>
	
				<div class="hui-form-items">
					<div class="hui-form-items-title">提交人</div>
					<input type="text" class="hui-input hui-input-clear" name="advice_user" checkType=" string "checkData="1,15" checkMsg="提交人应为1-15个字符 " placeholder="请填写提交人信息"/>
		    	</div>
		    	
		    	<div style="padding:15px 8px; ">
		            <button type="button" class="hui-button hui-primary hui-fr " id="submitBtn">提交</button>
		        </div>
		    	
		   </form>	
	
</div>

<script type="text/javascript">

hui.formInit();

hui('#submitBtn').click(function(){
    var res = huiFormCheck('#adviceForm');
    if(res){    	
    	hui.loading('数据提交中');
        var data = hui.getFormData('#adviceForm');
        hui.toast(JSON.stringify(data));
        hui.closeLoading();
    }
});

</script>
</body>
</html>

student/templates/student/announcement.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body style="background-color: #ffffff;">
	
	<div class="hui-common-title" style="margin-top:15px;">
			<div class="hui-common-title-line"></div>
			<div class="hui-common-title-txt " style="font-size: 40px;">查看通知</div>
			<div class="hui-common-title-line"></div>
	</div>

	<div class="hui-accordion" style="padding: 50px 300px;">			
        <div class="hui-accordion-title hui-primary" id="announcement_title" style="padding-bottom: 20px;">通知标题</div>
        <div class="hui-accordion-content hui-list">
            <ul id="announcement_list">
                <li><div class="hui-list-text" id="announcement_content" >通知详情</div></li>
            </ul>
        </div>
    </div>

	<div class="hui-accordion" style="padding: 50px 300px;">			
        <div class="hui-accordion-title hui-primary" id="announcement_title" style="padding-bottom: 20px;">通知标题</div>
        <div class="hui-accordion-content hui-list">
            <ul id="announcement_list">
                <li><div class="hui-list-text" id="announcement_content" >通知详情</div></li>
            </ul>
        </div>
    </div>




<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">

hui.accordion(false, false);


</script>
</body>
</html>

student/templates/student/article.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/error.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'student/js/hui-accordion.js' %}"></script>
<script src="{% static 'student/js/hui-tab.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'student/js/hui-form.js' %}"></script>
</head>
<body>

<div class="hui-common-title" style="margin-top:15px;">
    <div class="hui-common-title-line"></div>
    <div class="hui-common-title-txt " style="font-size: 40px;">{{ errorMsg }}</div>
    <div class="hui-common-title-line"></div>
</div>



<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>eMousika在线教学系统</title>
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'student/js/hui-accordion.js' %}"></script>
<script src="{% static 'student/js/hui-tab.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'student/js/hui-form.js' %}"></script>
</head>
<body style="background-color: #ffffff;">
<header>
	<div style="height: 50px; background-color: #000000; width: 100%" class="hui-flex">
		<div style="padding-left: 40px; padding-top: 7px;color: #ffffff;font-size: 24px; float: left">
            eMousika教学管理系统
        </div>

        <label style="color: #ffffff; padding-top: 10px; font-size: 20px; margin-left: 1500px;">
            您好   {{ username }}
        </label>

        <a style="padding-top: 10px; margin-left: 60px;" onclick="logOut" href="{% url 'student:login' %}">
            <u style="color: #ffffff; font-size: 20px;" >登出</u>
        </a>


	</div>	
</header>

<div class="hui-flex" style="padding-top: 1px; height: 900px;padding-left: 2px;">
	<!--左边的侧边栏-->
	<div id="sidebar" style="width: 300px; height: 100%; background-color: #696969;padding-top: 1px;" >

		<div class="hui-accordion" style="padding-right: 3px;">
		        <div class="hui-accordion-title" style="font-weight: 800;" >我的资源</div>
			        <div class="hui-accordion-content hui-list">
			            <ul>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="video">视频</div></li>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="article">文章</div></li>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="book">书籍</div></li>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="viewshare">学生分享</div></li>
			            </ul>
			        </div>
		</div>
		
		    	
		<div class="hui-accordion" style="padding-right: 3px;">  
				<div class="hui-accordion-title" style="font-weight: 800;">师生平台</div>
			        <div class="hui-accordion-content hui-list">
			            <ul>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="announcement">通知查看</div></li>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="advice">意见提交</div></li>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="slice">课件下载</div></li>  
                            <li><div class="hui-list-text" style="font-weight: 100;" id="writeshare">我要分享</div></li>
			            </ul>
			        </div>	
		</div>
		
		   
		<div class="hui-accordion" style="padding-right: 3px;">  
				<div class="hui-accordion-title" style="font-weight: 800;">课堂在线</div>
			        <div class="hui-accordion-content hui-list">
			            <ul>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="textpaper">试卷查看</div></li>          
			            </ul>
			        </div>
		</div>
		
		   
		<div class="hui-accordion" style="padding-right: 3px;">  
				<div class="hui-accordion-title" style="font-weight: 800;">个人中心</div>
			        <div class="hui-accordion-content hui-list">
			            <ul>
			                <li><div class="hui-list-text" style="font-weight: 100;" id="userinfor">信息管理</div></li> 
			                <li><div class="hui-list-text" style="font-weight: 100;" id="interest">兴趣管理</div></li> 	                
			            </ul>
			        </div>
		</div> 
		
		
		<div class="hui-accordion" style="padding-right: 3px;">  
				<div class="hui-accordion-title" style="font-weight: 800;">新闻推荐</div>
			        <div class="hui-accordion-content hui-list">
			            <ul>
			                <li><div class="hui-list-text" style="font-weight:100;" id="news">我的新闻</div></li>                
			            </ul>
			        </div> 
		</div> 

  
	</div>	

	<!--右边的显示页面-->
	<iframe id="frame" width="100%" height="100%"></iframe>

	
	
</div>


<script type="text/javascript">
    hui.accordion(false, true);
    // 取消浏览器的后退按钮

    //对侧边栏的按钮附加响应界面
    hui("#video").click(function(){
        hui("#frame").attr("src","/video")
    })

    hui("#article").click(function(){
        hui("#frame").attr("src","/article")
    })

    hui("#book").click(function(){
        hui("#frame").attr("src","/book")
    })

    hui("#viewshare").click(function(){
        hui("#frame").attr("src","/viewShare")
    })

    hui("#announcement").click(function(){
        hui("#frame").attr("src","/announcement")
    })

    hui("#advice").click(function(){
        hui("#frame").attr("src","/advice")
    })

    hui("#slice").click(function(){
        hui("#frame").attr("src","/slice")
    })

    hui("#writeshare").click(function(){
        hui("#frame").attr("src","/writeShare")
    })

    hui("#textpaper").click(function(){
        hui("#frame").attr("src","/textPaper")
    })

    hui("#userinfor").click(function(){
        hui("#frame").attr("src","/userInfor")
    })

    hui("#interest").click(function(){
        hui("#frame").attr("src","/interest")
    })

    hui("#news").click(function(){
        hui("#frame").attr("src","/news")
    })

    function logOut() {
        request.session.clear();
    }

</script>
</body>
</html>

student/templates/student/interest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/news.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>eMousika 注册</title>
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static '/student/js/hui-form.js' %}"></script>
</head>
<body style="background-image: url({% static 'student/img/loginBackground.jpg' %}">

<div class="hui-wrap">

	<form class="hui-form hui-fr" id="form1" style="padding:28px 10px; width: 500px; margin-right: 200px; margin-top: 250px;"  action="{% url 'student:register' %}" method="post">
        {% csrf_token %}
        <div class="hui-common-title" style=" font-size: 24px; color: #3388FF; font-weight: 700; padding-top: 20px;" >eMousika 教学系统</div>
        <div class="hui-form-items">
            <div class="hui-form-items-title" >用户名</div>
            <input type="text" class="hui-input hui-input-clear" name="username" placeholder="用户名" checkType="string" checkData="2,10" checkMsg="用户名应为2-10个字符" />
        </div>
        <div class="hui-form-items">
            <div class="hui-form-items-title">登录密码</div>
            <input type="password" class="hui-input hui-pwd-eye" name = "password" placeholder="登录密码" checkType="string" id="pwd" checkData="6,20"  checkMsg="密码应为6-20个字符" />
        </div>
        <div class="hui-form-items">
            <div class="hui-form-items-title">登录密码</div>
            <input type="password" class="hui-input hui-pwd-eye" placeholder="确认密码" checkType="sameWithId" checkData="pwd" checkMsg="两次密码不一致"  />
        </div>
        <div class="hui-form-items">
            <div class="hui-form-items-title">邮箱</div>
            <input type="email" class="hui-input hui-input-clear" name="email"  placeholder="您的邮箱" checkType = "email" checkMsg = "邮箱不合法"/>
        </div>
        <div style="margin-top: 20px; margin-left: 60px; margin-right: 60px;padding-bottom: 10px;">
            <button type="button" class="hui-button hui-primary hui-center-title" id="register">注册</button>
            <a href="{% url 'student:login' %}">
            <button type="button" class="hui-button hui-primary hui-center-title" id="submitBtn">登录</button>
            </a>
        </div>
    </form>

    {% if flag %}
        <script>
            hui.iconToast("用户已存在","warn");
        </script>
    {% endif %}

</div>

<script type="text/javascript">
hui.formInit();
//表单验证
hui('#register').click(function(){
    var res = huiFormCheck('#form1');
    //提交
    if(res){
        hui("#form1").dom[0].submit();
    }
});

</script>
</body>
</html>

student/templates/student/slice.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body style="background-color: #ffffff;" onload="getMaterial()">
<div class="hui-wrap" style="height: 100%;">
	
	<div class="hui-common-title" style="margin-top:15px;">
			<div class="hui-common-title-line"></div>
			<div class="hui-common-title-txt " style="font-size: 40px;">课件下载</div>
			<div class="hui-common-title-line"></div>
	</div>

	<!--课件列表-->	
	<div style="margin-top: 50px; margin-left: 300px; margin-right: 300px; padding-bottom: 5px; height: 50px;" class="hui-flex hui-primary" id="material">				
		<label style="margin-left: 100px; color: #ffffff; padding: 16px;" id="title">title</label>
		<label style="margin-left: 300px; margin-right: 300px; color: #ffffff; padding: 16px;" id="slice">slice_link</label>
		<label style="color: #ffffff; padding: 16px;" id="date">upload_date</label>
	</div>        

</div>

<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">

var data;
//页面接加载的时候请求课件数据，用作展示
function getMaterial(){
	var url = "http://127.0.0.1:8000/api/material/;"
	hui.getJSON(url,function(msg){
		hui.toast(msg);
	},
	function(e){
		hui.toast(e);
	});
}


</script>
</body>
</html>

student/templates/student/studentLogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>eMousika</title>
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static '/student/js/hui-form.js' %}"></script>
</head>
<body style="background-image: url({% static 'student/img/loginBackground.jpg' %}">

{% if msg %}
    <script type="text/javascript">
        hui.iconToast("用户不存在","warn");
    </script>
{% endif %}

<div class="hui-wrap">
	<form class="hui-form hui-fr" id="form1" style="padding:28px 10px; width: 500px; margin-right: 200px; margin-top: 250px;"  action="{% url 'student:login' %}" method="post">
        {% csrf_token %}
        <div class="hui-common-title" style=" font-size: 24px; color: #3388FF; font-weight: 700; padding-top: 20px;" >eMousika 教学系统</div>
        <div class="hui-form-items">
            <div class="hui-form-items-title" >用户名</div>
            <input type="text" class="hui-input hui-input-clear" name="username" placeholder="用户名" checkType="string" checkData="2,10" checkMsg="用户名应为2-10个字符" />
        </div>        
        <div class="hui-form-items">
            <div class="hui-form-items-title">登录密码</div>
            <input type="password" class="hui-input hui-pwd-eye" name = "password" placeholder="登录密码" checkType="string" id="pwd" checkData="6,20"  checkMsg="密码应为6-20个字符" />
        </div>
        <div style="margin-top: 20px; margin-left: 60px; margin-right: 60px;padding-bottom: 10px;">
            <button type="button" class="hui-button hui-primary hui-center-title" id="submitBtn">登录</button>
            <a href="{% url 'student:register' %}">
                <button type="button" class="hui-button hui-primary hui-center-title" id="register">注册</button>
            </a>
        </div>
    </form>
</div>


<script type="text/javascript">
hui.formInit();
//表单验证
hui("#submitBtn").click(function(){
    var res = huiFormCheck('#form1');
    //提交
    if(res){
        hui("#form1").dom[0].submit();
    }
});

window.history.forward(1)


</script>
</body>
</html>

student/templates/student/userInfor.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/video.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="{% static 'student/css/hui.css' %}" />
<script src="{% static 'student/js/hui.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="{% static 'student/js/hui-accordion.js' %}"></script>
<script type="text/javascript" src="{% static 'student/js/hui-form.js' %}"></script>
</head>
<body style="background-color: #ffffff">

<style type="text/css">
table{
font-size:12px;
}
table{
table-layout:fixed;
empty-cells:show;
border-collapse: collapse;
margin:0 auto;
}
td{
height:30px;
}
h1,h2,h3{
font-size:12px;
margin:0;
padding:0;
}
.table{
border:1px solid #cad9ea;
color:#666;
}
.table th {
background-repeat:repeat-x;
height:30px;
}
.table td,.table th{
border:1px solid #cad9ea;
padding:0 1em 0;
}
.table tr.alter{
background-color:#f5fafe;
}
</style>

	<div class="hui-common-title" style="margin-top:15px;">
			<div class="hui-common-title-line"></div>
			<div class="hui-common-title-txt " style="font-size: 40px;">视频查看</div>
			<div class="hui-common-title-line"></div>
    </div>


<table width="90%" class="table" style="margin-top: 100px;" id="mytable">
    <tr>
    <th>名称</th>
    <th>领域</th>
    <th>来源</th>
    <th>简介</th>
    <th>在线链接</th>
    <th>下载链接</th>
    <th>发布时间</th>
    </tr>

    {% for video in videos %}
        <tr>
            <td>{{ video.title }}</td>
            <td>{{ video.area }}</td>
            <td>{{ video.origin }}</td>
            <td>{{ video.summary }}</td>
            <td><a href="{{ video.link }}"> <u>点击查看</u></a></td>
            <td><a href="{{ srcLink }}{{ video.resource }}"><u>下载资源</u></a></td>
            <td>{{ video.pubtime }}</td>
        </tr>
    {% endfor %}

</table>

<script type="text/javascript">


</script>
</body>
</html>

student/templates/student/viewshare.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>

student/templates/student/writeshare.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title></title>
<link rel="stylesheet" type="text/css" href="./css/hui.css" />
</head>
<body>
<header>
    
</header>





<script src="./js/hui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" src="./js/hui-accordion.js"></script>
<script src="./js/hui-tab.js" type="text/javascript"></script>
<script type="text/javascript" src="./js/hui-form.js"></script>
<script type="text/javascript">




</script>
</body>
</html>